from pydantic import BaseModel

from app.models.cart import Cart
from app.models.recommendation import OfferRecommendation


class CartContext(BaseModel):
    """
    Trusted cart information displayed to the marketer.

    This data comes directly from the cart dataset.
    It is not generated by the LLM.
    """

    fan_id: str
    seats: int
    section: str
    cart_value: float
    abandoned_hours: float
    lifetime_tickets: int
    days_since_last_purchase: int | None
    email_opt_in: bool


class RecommendationResponse(BaseModel):
    """
    API response consumed by the marketer UI.

    Separates the agent recommendation from the
    underlying cart facts used to make the decision.
    """

    recommendation: OfferRecommendation
    cart_context: CartContext

    @classmethod
    def from_cart_and_recommendation(
        cls,
        cart: Cart,
        recommendation: OfferRecommendation,
    ) -> "RecommendationResponse":

        return cls(
            recommendation=recommendation,
            cart_context=CartContext(
                fan_id=cart.fan_id,
                seats=cart.seats,
                section=cart.section,
                cart_value=cart.cart_value,
                abandoned_hours=cart.abandoned_hours,
                lifetime_tickets=cart.lifetime_tickets,
                days_since_last_purchase=(
                    cart.days_since_last_purchase
                ),
                email_opt_in=cart.email_opt_in,
            ),
        )